version: '3'
services:
  frontend:
    image: 0d1n92/marcatempo-vue:latest

    ports:
       - "8080:8080"
    networks:
    - marcatempo
  database:
    image: mysql:8.0
    ports:
        - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: db_marcatempo
    networks:
    - marcatempo
  backend:
    image: 0d1n92/marcatempo-asp:latest
    ports:
      - "5200:80"
    networks:
      - marcatempo
    depends_on:
        - database
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - marcatempo
    depends_on:
      - backend
networks:
    marcatempo:

